export const supportedLanguages = {
    en: "English",
    es: "Spanish",
    // fr: "French",
    // de: "German",
    // it: "Italian",
};

export const posMap: Record<string, string> = {
    ADJ: "Adjective",
    ADP: "Adposition",
    ADV: "Adverb",
    AUX: "Auxiliary",
    CCONJ: "Coordinating conjunction",
    DET: "Determiner",
    INTJ: "Interjection",
    NOUN: "Noun",
    NUM: "Numeral",
    PART: "Particle",
    PRON: "Pronoun",
    PROPN: "Proper noun",
    PUNCT: "Punctuation",
    SCONJ: "Subordinating conjunction",
    SYM: "Symbol",
    VERB: "Verb",
    X: "Other",
};

export const depMap: Record<string, string> = {
    ROOT: "",
    acl: "clausal modifier of noun (adjectival clause)",
    acomp: "adjectival complement",
    advcl: "adverbial clause modifier",
    advmod: "adverbial modifier",
    agent: "agent",
    amod: "adjectival modifier",
    appos: "appositional modifier",
    attr: "attribute",
    aux: "auxiliary",
    auxpass: "auxiliary (passive)",
    case: "case marking",
    cc: "coordinating conjunction",
    ccomp: "clausal complement",
    compound: "compound",
    conj: "conjunct",
    cop: "copula", // ADDED in es
    csubj: "clausal subject",
    csubjpass: "clausal subject (passive)",
    dative: "dative",
    dep: "unclassified dependent",
    det: "determiner",
    dobj: "direct object",
    expl: "expletive",
    "expl:pass": "expletive (passive)", // ADDED in es
    fixed: "fixed multiword expression", // ADDED in es
    flat: "flat multiword expression", // ADDED in es
    intj: "interjection",
    iobj: "indirect object", // ADDED in es
    mark: "marker",
    meta: "meta modifier",
    neg: "negation modifier",
    nmod: "modifier of nominal",
    npadvmod: "noun phrase as adverbial modifier",
    nsubj: "nominal subject",
    nsubjpass: "nominal subject (passive)",
    nummod: "numeric modifier",
    oprd: "object predicate",
    obj: "object", // ADDED in es
    obl: "oblique nominal", // ADDED in es
    parataxis: "parataxis",
    pcomp: "complement of a preposition",
    pobj: "object of a preposition",
    poss: "possession modifier",
    preconj: "pre-correlative conjunction",
    predet: "pre-determiner",
    prep: "prepositional modifier",
    prt: "particle",
    punct: "punctuation",
    quantmod: "modifier of quantifier",
    relcl: "relative clause modifier",
    xcomp: "open clausal complement",
};

export const morphToAbbreviation: Record<string, string> = {
    abbreviation: "Abbr",
    abessive: "Case",
    ablative: "Case",
    "absolute superlative": "Degree",
    absolutive: "Case",
    accusative: "Case",
    active: "Voice",
    "actor-focus voice": "Voice",
    additive: "Case",
    adelative: "Case",
    adessive: "Case",
    adlative: "Case",
    admirative: "Mood",
    "adverbial participle": "VerbForm",
    affirmative: "Polarity",
    allative: "Case",
    animate: "Animacy",
    antipassive: "Voice",
    aorist: "Tense",
    article: "PronType",
    aspect: "Aspect",
    associative: "Case",
    augmentative: "Degree",
    "bantu noun class": "NounClass",
    benefactive: "Case",
    "beneficiary-focus voice": "Voice",
    cardinal: "NumType",
    caritive: "Case",
    case: "Case",
    "causative case": "Case",
    "causative voice": "Voice",
    clusivity: "Clusivity",
    "collective noun": "Number",
    "collective numeral": "NumType",
    "collective pronominal": "PronType",
    comitative: "Case",
    "common gender": "Gender",
    "comparative case": "Case",
    "comparative degree": "Degree",
    "complex definiteness": "Definite",
    conditional: "Mood",
    conjunctive: "Mood",
    considerative: "Case",
    "construct state": "Definite",
    converb: "VerbForm",
    "count plural": "Number",
    "counting form": "Number",
    dative: "Case",
    definite: "Definite",
    definiteness: "Definite",
    "degree of comparison": "Degree",
    delative: "Case",
    demonstrative: "PronType",
    desiderative: "Mood",
    destinative: "Case",
    diminutive: "Degree",
    "direct case": "Case",
    "direct voice": "Voice",
    "directional allative": "Case",
    "distributive case": "Case",
    "distributive numeral": "NumType",
    dual: "Number",
    elative: "Case",
    "elevated referent": "Polite",
    emphatic: "PronType",
    "equative case": "Case",
    "equative degree": "Degree",
    ergative: "Case",
    essive: "Case",
    evidentiality: "Evident",
    exclamative: "PronType",
    exclusive: "Clusivity",
    factive: "Case",
    feminine: "Gender",
    "finite verb": "VerbForm",
    "first person": "Person",
    firsthand: "Evident",
    "foreign word": "Foreign",
    formal: "Polite",
    "fourth person": "Person",
    fraction: "NumType",
    frequentative: "Aspect",
    future: "Tense",
    gender: "Gender",
    genitive: "Case",
    gerund: "VerbForm",
    gerundive: "VerbForm",
    "greater paucal": "Number",
    "greater plural": "Number",
    habitual: "Aspect",
    human: "Animacy",
    "humbled speaker": "Polite",
    illative: "Case",
    imperative: "Mood",
    "imperfect tense": "Tense",
    "imperfective aspect": "Aspect",
    inanimate: "Animacy",
    inclusive: "Clusivity",
    indefinite: "Definite",
    "indefinite pronominal": "PronType",
    indicative: "Mood",
    inelative: "Case",
    inessive: "Case",
    infinitive: "VerbForm",
    informal: "Polite",
    injunctive: "Mood",
    inlative: "Case",
    instructive: "Case",
    instrumental: "Case",
    "interrogative mood": "Mood",
    "interrogative pronominal": "PronType",
    "inverse number": "Number",
    "inverse voice": "Voice",
    irrealis: "Mood",
    iterative: "Aspect",
    jussive: "Mood",
    lative: "Case",
    "location-focus voice": "Voice",
    locative: "Case",
    masculine: "Gender",
    masdar: "VerbForm",
    "mass noun": "Number",
    "middle voice": "Voice",
    modality: "Mood",
    mood: "Mood",
    motivative: "Case",
    "multiplicative numeral": "NumType",
    narrative: "Evident",
    necessitative: "Mood",
    "negative polarity": "Polarity",
    "negative pronominal": "PronType",
    neuter: "Gender",
    nominative: "Case",
    "non-finite verb": "VerbForm",
    "non-firsthand": "Evident",
    "non-human": "Animacy",
    "non-past": "Tense",
    "non-specific indefinite": "Definite",
    "noun class": "NounClass",
    number: "Number",
    "numeral type": "NumType",
    "oblique case": "Case",
    optative: "Mood",
    ordinal: "NumType",
    participle: "VerbForm",
    partitive: "Case",
    passive: "Voice",
    past: "Tense",
    "past perfect": "Tense",
    "patient-focus voice": "Voice",
    paucal: "Number",
    "perfective aspect": "Aspect",
    perlative: "Case",
    person: "Person",
    personal: "PronType",
    pluperfect: "Tense",
    plural: "Number",
    "plurale tantum": "Number",
    polarity: "Polarity",
    politeness: "Polite",
    "positive degree": "Degree",
    "positive polarity": "Polarity",
    possessive: "Poss",
    potential: "Mood",
    present: "Tense",
    preterite: "Tense",
    privative: "Case",
    progressive: "Aspect",
    prolative: "Case",
    "pronominal type": "PronType",
    prospective: "Aspect",
    "purposive case": "Case",
    "purposive mood": "Mood",
    quantifier: "NumType",
    "quantitative plural": "Number",
    quotative: "Mood",
    "range numeral": "NumType",
    realis: "Mood",
    "reciprocal pronominal": "PronType",
    "reciprocal voice": "Voice",
    "reduced definiteness": "Definite",
    reflexive: "Reflex",
    register: "Polite",
    relative: "PronType",
    "second person": "Person",
    "set numeral": "NumType",
    singular: "Number",
    "singulare tantum": "Number",
    "specific indefinite": "Definite",
    subelative: "Case",
    subessive: "Case",
    subjunctive: "Mood",
    sublative: "Case",
    superelative: "Case",
    superessive: "Case",
    "superlative case": "Case",
    "superlative degree": "Degree",
    supine: "VerbForm",
    temporal: "Case",
    tense: "Tense",
    "terminal allative": "Case",
    terminative: "Case",
    "third person": "Person",
    total: "PronType",
    transgressive: "VerbForm",
    translative: "Case",
    trial: "Number",
    typo: "Typo",
    uter: "Gender",
    "verb form": "VerbForm",
    "verbal adjective": "VerbForm",
    "verbal adverb": "VerbForm",
    "verbal noun": "VerbForm",
    vocative: "Case",
    voice: "Voice",
    "zero person": "Person",
};

export const abbreviationToMorphOptions: Record<
    string,
    Record<string, string>
> = {
    Abbr: {
        __description: "abbreviation",
        Yes: "it is abbreviation",
    },
    AdpType: {
        __description: "adposition type",
        Prep: "preposition",
        Post: "postposition",
        Circ: "circumposition",
        Voc: "vocalized preposition",
    },
    PrepCase: {
        __description: "case form sensitive to prepositions",
        Npr: "non-prepositional case",
        Pre: "propositional case",
    },
    PunctType: {
        __description: "punctuation type",
        Peri: "period at the end of sentence or clause",
        Elip: "ellipsis",
        Qest: "question mark",
        Excl: "exclamation mark",
        Quot: "quotation marks (various sorts in various languages)",
        Brck: "bracket",
        Comm: "comma",
        Colo: "colon",
        Semi: "semicolon",
        Dash: "dash, hyphen",
        Slsh: "slash or backslash",
    },
    Case: {
        __description: "case",
        Nom: "nominative / direct",
        Acc: "accusative / oblique",
        Abs: "absolutive",
        Erg: "ergative",
        Dat: "dative",
        Gen: "genitive",
        Voc: "vocative",
        Ins: "instrumental / instructive",
        Par: "partitive",
        Dis: "distributive",
        Ess: "essive / prolative",
        Tra: "translative / factive",
        Com: "comitative / associative",
        Abe: "abessive / caritive / privative",
        Cau: "causative / motivative / purposive",
        Ben: "benefactive / destinative",
        Cns: "considerative",
        Cmp: "comparative",
        Equ: "equative",
        Loc: "locative",
        Lat: "lative / directional allative",
        Ter: "terminative / terminal allative",
        Ine: "inessive",
        Ill: "illative / inlative",
        Ela: "elative / inelative",
        Add: "additive",
        Ade: "adessive",
        All: "allative / adlative",
        Abl: "ablative / adelative",
        Sup: "superessive",
        Spl: "superlative",
        Del: "delative / superelative",
        Sub: "subessive",
        Sbl: "sublative",
        Sbe: "subelative",
        Per: "perlative",
        Tem: "temporal",
    },
    Degree: {
        __description: "degree",
        Pos: "positive, first degree",
        Equ: "equative",
        Cmp: "comparative, second degree",
        Sup: "superlative, third degree",
        Abs: "absolute superlative",
        Dim: "diminutive",
        Aug: "augmentative",
    },
    Voice: {
        __description: "voice",
        Act: "active or actor-focus voice",
        Mid: "middle voice",
        Rcp: "reciprocal voice",
        Pass: "passive or patient-focus voice",
        Antip: "antipassive voice",
        Lfoc: "location-focus voice",
        Bfoc: "beneficiary-focus voice",
        Dir: "direct voice",
        Inv: "inverse voice",
        Cau: "causative voice",
    },
    Mood: {
        __description: "mood",
        Ind: "indicative or realis",
        Imp: "imperative",
        Cnd: "conditional",
        Pot: "potential",
        Sub: "subjunctive / conjunctive",
        Jus: "jussive / injunctive",
        Prp: "purposive",
        Qot: "quotative",
        Opt: "optative",
        Des: "desiderative",
        Nec: "necessitative",
        Int: "interrogative",
        Irr: "irrealis",
        Adm: "admirative",
    },
    VerbForm: {
        __description: "form of verb or deverbative",
        Fin: "finite verb",
        Inf: "infinitive",
        Sup: "supine",
        Part: "participle, verbal adjective",
        Conv: "converb, transgressive, adverbial participle, verbal adverb",
        Gdv: "gerundive",
        Ger: "gerund",
        Vnoun: "verbal noun, masdar",
    },
    Polarity: {
        __description: "polarity",
        Pos: "positive, affirmative",
        Neg: "negative",
    },
    Animacy: {
        __description: "animacy",
        Anim: "animate",
        Inan: "inanimate",
        Hum: "human",
        Nhum: "non-human",
    },
    Tense: {
        __description: "tense",
        Past: "past tense / preterite / aorist",
        Pres: "present / non-past tense / aorist",
        Fut: "future tense",
        Imp: "imperfect",
        Pqp: "pluperfect",
    },
    PronType: {
        __description: "pronominal type",
        Prs: "personal or possessive personal pronoun or determiner",
        Rcp: "reciprocal pronoun",
        Art: "article",
        Int: "interrogative pronoun, determiner, numeral or adverb",
        Rel: "relative pronoun, determiner, numeral or adverb",
        Exc: "exclamative determiner",
        Dem: "demonstrative pronoun, determiner, numeral or adverb",
        Emp: "emphatic determiner",
        Tot: "total (collective) pronoun, determiner or adverb",
        Neg: "negative pronoun, determiner or adverb",
        Ind: "indefinite pronoun, determiner, numeral or adverb",
    },
    Aspect: {
        __description: "aspect",
        Imp: "imperfect aspect",
        Perf: "perfect aspect",
        Prosp: "prospective aspect",
        Prog: "progressive aspect",
        Hab: "habitual aspect",
        Iter: "iterative / frequentative aspect",
    },
    NounClass: {
        __description: "noun class",
        Bantu1: "singular, persons",
        Bantu2: "plural, persons",
        Bantu3: "singular, plants, thin objects",
        Bantu4: "plural, plants, thin objects",
        Bantu5: "singular, fruits, round objects, paired things",
        Bantu6: "plural, fruits, round objects, paired things",
        Bantu7: "singular, things, diminutives",
        Bantu8: "plural, things, diminutives",
        Bantu9: "singular, animals, things",
        Bantu10: "plural, animals, things",
        Bantu11: "long thin objects, natural phenomena, abstracts",
        Bantu12: "singular, small things, diminutives",
        Bantu13: "plural or mass, small amount of mass",
        Bantu14: "plural, diminutives",
        Bantu15: "verbal nouns, infinitives",
        Bantu16: "definite location, close to something",
        Bantu17: "indefinite location, direction, movement",
        Bantu18: "definite location, inside something",
        Bantu19: "little bit of, pejorative plural",
        Bantu20: "singular, augmentatives",
        Bantu21: "singular, augmentatives, derogatives",
        Bantu22: "plural, augmentatives",
        Bantu23: "location with place names",
        Wol1: "Wolof noun class 1/k (singular human)",
        Wol2: "Wolof noun class 2/ñ (plural human)",
        Wol3: "Wolof noun class 3/g (singular)",
        Wol4: "Wolof noun class 4/j (singular)",
        Wol5: "Wolof noun class 5/b (singular)",
        Wol6: "Wolof noun class 6/m (singular)",
        Wol7: "Wolof noun class 7/l (singular)",
        Wol8: "Wolof noun class 8/y (plural non-human)",
        Wol9: "Wolof noun class 9/s (singular)",
        Wol10: "Wolof noun class 10/w (singular)",
        Wol11: "Wolof noun class 11/f (location)",
        Wol12: "Wolof noun class 12/n (manner)",
    },
    NumType: {
        __description: "numeral type",
        Card: "cardinal number or corresponding interrogative / relative / indefinite / demonstrative word",
        Ord: "ordinal number or corresponding interrogative / relative / indefinite / demonstrative word",
        Mult: "multiplicative numeral or corresponding interrogative / relative / indefinite / demonstrative word",
        Frac: "fraction",
        Sets: "number of sets of things; collective numeral",
        Dist: "distributive numeral",
        Range: "range of values",
    },
    Clusivity: {
        __description: "clusivity",
        In: "inclusive",
        Ex: "exclusive",
    },
    Number: {
        __description: "number",
        Sing: "singular number",
        Plur: "plural number",
        Dual: "dual number",
        Tri: "trial number",
        Pauc: "paucal number",
        Grpa: "greater paucal number",
        Grpl: "greater plural number",
        Inv: "inverse number",
        Count: "count plural",
        Ptan: "plurale tantum",
        Coll: "collective / mass / singulare tantum",
    },
    Gender: {
        __description: "gender",
        Masc: "masculine gender",
        Fem: "feminine gender",
        Neut: "neuter gender",
        Com: "common gender",
    },
    Definite: {
        __description: "definiteness or state",
        Ind: "indefinite",
        Spec: "specific indefinite",
        Def: "definite",
        Cons: "construct state / reduced definiteness",
        Com: "complex",
    },
    Polite: {
        __description: "politeness",
        Infm: "informal register",
        Form: "formal register",
        Elev: "referent elevating",
        Humb: "speaker humbling",
    },
    Evident: {
        __description: "evidentiality",
        Fh: "firsthand",
        Nfh: "non-firsthand",
    },
    Person: {
        "0": "zero person",
        "1": "first person",
        "2": "second person",
        "3": "third person",
        "4": "fourth person",
        __description: "person",
    },
    Foreign: {
        __description: "is this a foreign word?",
        Yes: "it is foreign",
    },
    Poss: {
        __description: "possessive",
        Yes: "it is possessive",
    },
    Reflex: {
        __description: "reflexive",
        Yes: "it is reflexive",
    },
    Typo: {
        __description: "is this a misspelled word?",
        Yes: "it is typo",
    },
};

export const abbreviationToMorph: Record<string, string[]> = {
    Abbr: ["abbreviation"],
    Case: [
        "abessive",
        "ablative",
        "absolutive",
        "accusative",
        "additive",
        "adelative",
        "adessive",
        "adlative",
        "allative",
        "associative",
        "benefactive",
        "caritive",
        "case",
        "causative case",
        "comitative",
        "comparative case",
        "considerative",
        "dative",
        "delative",
        "destinative",
        "direct case",
        "directional allative",
        "distributive case",
        "elative",
        "equative case",
        "ergative",
        "essive",
        "factive",
        "genitive",
        "illative",
        "inelative",
        "inessive",
        "inlative",
        "instructive",
        "instrumental",
        "lative",
        "locative",
        "motivative",
        "nominative",
        "oblique case",
        "partitive",
        "perlative",
        "privative",
        "prolative",
        "purposive case",
        "subelative",
        "subessive",
        "sublative",
        "superelative",
        "superessive",
        "superlative case",
        "temporal",
        "terminal allative",
        "terminative",
        "translative",
        "vocative",
    ],
    Degree: [
        "absolute superlative",
        "augmentative",
        "comparative degree",
        "degree of comparison",
        "diminutive",
        "equative degree",
        "positive degree",
        "superlative degree",
    ],
    Voice: [
        "active",
        "actor-focus voice",
        "antipassive",
        "beneficiary-focus voice",
        "causative voice",
        "direct voice",
        "inverse voice",
        "location-focus voice",
        "middle voice",
        "passive",
        "patient-focus voice",
        "reciprocal voice",
        "voice",
    ],
    Mood: [
        "admirative",
        "conditional",
        "conjunctive",
        "desiderative",
        "imperative",
        "indicative",
        "injunctive",
        "interrogative mood",
        "irrealis",
        "jussive",
        "modality",
        "mood",
        "necessitative",
        "optative",
        "potential",
        "purposive mood",
        "quotative",
        "realis",
        "subjunctive",
    ],
    VerbForm: [
        "adverbial participle",
        "converb",
        "finite verb",
        "gerund",
        "gerundive",
        "infinitive",
        "masdar",
        "non-finite verb",
        "participle",
        "supine",
        "transgressive",
        "verb form",
        "verbal adjective",
        "verbal adverb",
        "verbal noun",
    ],
    Polarity: [
        "affirmative",
        "negative polarity",
        "polarity",
        "positive polarity",
    ],
    Animacy: ["animate", "human", "inanimate", "non-human"],
    Tense: [
        "aorist",
        "future",
        "imperfect tense",
        "non-past",
        "past",
        "past perfect",
        "pluperfect",
        "present",
        "preterite",
        "tense",
    ],
    PronType: [
        "article",
        "collective pronominal",
        "demonstrative",
        "emphatic",
        "exclamative",
        "indefinite pronominal",
        "interrogative pronominal",
        "negative pronominal",
        "personal",
        "pronominal type",
        "reciprocal pronominal",
        "relative",
        "total",
    ],
    Aspect: [
        "aspect",
        "frequentative",
        "habitual",
        "imperfective aspect",
        "iterative",
        "perfective aspect",
        "progressive",
        "prospective",
    ],
    NounClass: ["bantu noun class", "noun class"],
    NumType: [
        "cardinal",
        "collective numeral",
        "distributive numeral",
        "fraction",
        "multiplicative numeral",
        "numeral type",
        "ordinal",
        "quantifier",
        "range numeral",
        "set numeral",
    ],
    Clusivity: ["clusivity", "exclusive", "inclusive"],
    Number: [
        "collective noun",
        "count plural",
        "counting form",
        "dual",
        "greater paucal",
        "greater plural",
        "inverse number",
        "mass noun",
        "number",
        "paucal",
        "plural",
        "plurale tantum",
        "quantitative plural",
        "singular",
        "singulare tantum",
        "trial",
    ],
    Gender: [
        "common gender",
        "feminine",
        "gender",
        "masculine",
        "neuter",
        "uter",
    ],
    Definite: [
        "complex definiteness",
        "construct state",
        "definite",
        "definiteness",
        "indefinite",
        "non-specific indefinite",
        "reduced definiteness",
        "specific indefinite",
    ],
    Polite: [
        "elevated referent",
        "formal",
        "humbled speaker",
        "informal",
        "politeness",
        "register",
    ],
    Evident: ["evidentiality", "firsthand", "narrative", "non-firsthand"],
    Person: [
        "first person",
        "fourth person",
        "person",
        "second person",
        "third person",
        "zero person",
    ],
    Foreign: ["foreign word"],
    Poss: ["possessive"],
    Reflex: ["reflexive"],
    Typo: ["typo"],
};
